"""Initial migration 2

Revision ID: 0de838fc6185
Revises: 
Create Date: 2020-10-22 21:38:57.980164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de838fc6185'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('follows',
    sa.Column('fid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower', sa.Integer(), nullable=False),
    sa.Column('following', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['following'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_table('posts',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('follows')
    op.drop_table('users')
    # ### end Alembic commands ###
